models/Operasional.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "operasional".
 *
 * @property int $id
 * @property int $id_hari
 * @property string $tanggal
 */
class Operasional extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'operasional';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            ['id_hari','unique','message' => '{attribute} Sudah Di Inputkan, Silahkan Pilih Hari Yang Lain'],
            [['id_hari'], 'required'],
            [['id_hari'], 'integer'],
            [['tanggal'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_hari' => 'Hari',
            'tanggal' => 'Tanggal Input',
        ];
    }

    public function getManyJamOperasional()
    {
        return $this->hasMany(JamOperasional::class,['id_operasional' => 'id']);
    }
}

controllers/JamOperasionalController.php
<?php

namespace app\controllers;

use Yii;
use app\models\JamOperasional;
use app\models\JamOperasionalSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

use app\components\Helper;
use kartik\mpdf\Pdf;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Fill;

/**
 * JamOperasionalController implements the CRUD actions for JamOperasional model.
 */
class JamOperasionalController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [  
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['index','view','create','update','delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all JamOperasional models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new JamOperasionalSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single JamOperasional model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new JamOperasional model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($id_operasional)
    {
        $model = new JamOperasional(['id_operasional' => $id_operasional]);

        $referrer = Yii::$app->request->referrer;

        if ($model->load(Yii::$app->request->post())) {
            $referrer = $_POST['referrer'];

            if ($model->save()) {
                Yii::$app->session->setFlash('success','Data berhasil disimpan.');
                return $this->redirect($referrer);
            }

            Yii::$app->session->setFlash('error','Data gagal disimpan. Silahkan periksa kembali isian Anda.');
        }

        return $this->render('create', [
            'model' => $model,
            'referrer'=>$referrer
        ]);

    }

    /**
     * Updates an existing JamOperasional model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $referrer = Yii::$app->request->referrer;

        if ($model->load(Yii::$app->request->post())) {
            $referrer = $_POST['referrer'];

            if ($model->save()) {
                Yii::$app->session->setFlash('success','Data berhasil disimpan.');
                return $this->redirect($referrer);
            }

            Yii::$app->session->setFlash('error','Data gagal disimpan. Silahkan periksa kembali isian Anda.');
        }

        return $this->render('update', [
            'model' => $model,
            'referrer'=>$referrer
        ]);

    }

    /**
     * Deletes an existing JamOperasional model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);

        if ($model->delete()) {
            Yii::$app->session->setFlash('success','Data berhasil dihapus');
        } else {
            Yii::$app->session->setFlash('error','Data gagal dihapus');
        }

        return $this->redirect(Yii::$app->request->referrer);
    }

    /**
     * Finds the JamOperasional model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return JamOperasional the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = JamOperasional::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function exportExcel($params)
    {
    $spreadsheet = new Spreadsheet();

    $spreadsheet->setActiveSheetIndex(0);

    $sheet = $spreadsheet->getActiveSheet();

    $setBorderArray = array(
    'borders' => array(
    'allBorders' => array(
    'borderStyle' => Border::BORDER_THIN,
    'color' => array('argb' => '000000'),
    ),
    ),
    );


    $sheet->getColumnDimension('A')->setWidth(10);
            $sheet->getColumnDimension('B')->setWidth(20);
                $sheet->getColumnDimension('C')->setWidth(20);
                $sheet->getColumnDimension('D')->setWidth(20);
        
    $sheet->setCellValue('A3', 'No');
            $sheet->setCellValue('B3', 'Id Operasional');
                $sheet->setCellValue('C3', 'Jam Buka');
                $sheet->setCellValue('D3', 'Jam Tutup');
        
    $sheet->setCellValue('A1', 'Data JamOperasional');

    $sheet->mergeCells('A1:D1');

    $sheet->getStyle('A1:D3')->getFont()->setBold(true);
    $sheet->getStyle('A1:D3')->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);

    $row = 3;
    $i=1;

    $searchModel = new JamOperasionalSearch();

    foreach($searchModel->getQuerySearch($params)->all() as $data){
    $row++;
    $sheet->setCellValue('A' . $row, $i);
            $sheet->setCellValue('B' . $row, $data->id_operasional);
                $sheet->setCellValue('C' . $row, $data->jam_buka);
                $sheet->setCellValue('D' . $row, $data->jam_tutup);
        
    $i++;
    }

    $sheet->getStyle('A3:D' . $row)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
    $sheet->getStyle('D3:D' . $row)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
    $sheet->getStyle('E3:D' . $row)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);


    $sheet->getStyle('C' . $row)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);

    $sheet->getStyle('A3:D' . $row)->applyFromArray($setBorderArray);

    $filename = time() . '_Data-Excel.xlsx';
    $path = 'exports/' . $filename;
    $writer = new Xlsx($spreadsheet);
    $writer->save($path);

    return $this->redirect($path);
    }

}

controllers/OperasionalController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Operasional;
use app\models\OperasionalSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

use app\components\Helper;
use kartik\mpdf\Pdf;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Fill;

/**
 * OperasionalController implements the CRUD actions for Operasional model.
 */
class OperasionalController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [  
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['index','view','create','update','delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Operasional models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new OperasionalSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Operasional model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Operasional model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Operasional();

        $referrer = Yii::$app->request->referrer;

        if ($model->load(Yii::$app->request->post())) {
            $referrer = $_POST['referrer'];
            $model->tanggal = date('Y-m-d H:i:s');

            if ($model->save()) {
                Yii::$app->session->setFlash('success','Data berhasil disimpan.');
                return $this->redirect($referrer);
            }

            Yii::$app->session->setFlash('error','Data gagal disimpan. Silahkan periksa kembali isian Anda.');
        }

        return $this->render('create', [
            'model' => $model,
            'referrer'=>$referrer
        ]);

    }

    /**
     * Updates an existing Operasional model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $referrer = Yii::$app->request->referrer;

        if ($model->load(Yii::$app->request->post())) {
            $referrer = $_POST['referrer'];
            $model->tanggal = date('Y-m-d H:i:s');

            if ($model->save()) {
                Yii::$app->session->setFlash('success','Data berhasil disimpan.');
                return $this->redirect($referrer);
            }

            Yii::$app->session->setFlash('error','Data gagal disimpan. Silahkan periksa kembali isian Anda.');
        }

        return $this->render('update', [
            'model' => $model,
            'referrer'=>$referrer
        ]);

    }

    /**
     * Deletes an existing Operasional model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);

        if ($model->delete()) {
            Yii::$app->session->setFlash('success','Data berhasil dihapus');
        } else {
            Yii::$app->session->setFlash('error','Data gagal dihapus');
        }

        return $this->redirect(Yii::$app->request->referrer);
    }

    /**
     * Finds the Operasional model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Operasional the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Operasional::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function exportExcel($params)
    {
    $spreadsheet = new Spreadsheet();

    $spreadsheet->setActiveSheetIndex(0);

    $sheet = $spreadsheet->getActiveSheet();

    $setBorderArray = array(
    'borders' => array(
    'allBorders' => array(
    'borderStyle' => Border::BORDER_THIN,
    'color' => array('argb' => '000000'),
    ),
    ),
    );


    $sheet->getColumnDimension('A')->setWidth(10);
            $sheet->getColumnDimension('B')->setWidth(20);
                $sheet->getColumnDimension('C')->setWidth(20);
        
    $sheet->setCellValue('A3', 'No');
            $sheet->setCellValue('B3', 'Id Hari');
                $sheet->setCellValue('C3', 'Tanggal');
        
    $sheet->setCellValue('A1', 'Data Operasional');

    $sheet->mergeCells('A1:C1');

    $sheet->getStyle('A1:C3')->getFont()->setBold(true);
    $sheet->getStyle('A1:C3')->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);

    $row = 3;
    $i=1;

    $searchModel = new OperasionalSearch();

    foreach($searchModel->getQuerySearch($params)->all() as $data){
    $row++;
    $sheet->setCellValue('A' . $row, $i);
            $sheet->setCellValue('B' . $row, $data->id_hari);
                $sheet->setCellValue('C' . $row, $data->tanggal);
        
    $i++;
    }

    $sheet->getStyle('A3:C' . $row)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
    $sheet->getStyle('D3:C' . $row)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
    $sheet->getStyle('E3:C' . $row)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);


    $sheet->getStyle('C' . $row)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);

    $sheet->getStyle('A3:C' . $row)->applyFromArray($setBorderArray);

    $filename = time() . '_Data-Excel.xlsx';
    $path = 'exports/' . $filename;
    $writer = new Xlsx($spreadsheet);
    $writer->save($path);

    return $this->redirect($path);
    }

}

views/operasional/_form.php
<?php

use yii\helpers\Html;
use kartik\form\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Operasional */
/* @var $form yii\widgets\ActiveForm */
?>

<?php $form = ActiveForm::begin([
    'type' => 'horizontal',
    'enableAjaxValidation' => false,
    'enableClientValidation' => false,
    'fieldConfig' => [
        'horizontalCssClasses' => [
            'label' => 'col-sm-2',
            'wrapper' => 'col-sm-4',
            'error' => '',
            'hint' => '',
        ],
    ]
]); ?>

<div class="operasional-form box box-primary">

    <div class="box-header with-border">
        <h3 class="box-title">Form Operasional</h3>
    </div>
	<div class="box-body">

        <?= $form->errorSummary($model); ?>

        <?= $form->field($model, 'id_hari')->dropDownList(app\components\Helper::getListHariDropdown(), ['prompt' => '-- Pilih Hari --']); ?>

        <?= Html::hiddenInput('referrer',$referrer); ?>

	</div>
    <div class="box-footer">
        <div class="col-sm-offset-2 col-sm-3">
            <?= Html::submitButton('<i class="fa fa-check"></i> Simpan',['class' => 'btn btn-success btn-flat']) ?>
        </div>
    </div>

</div>

<?php ActiveForm::end(); ?>

views/operasional/_list-jam-operasional.php
<?php 

use yii\helpers\Html;
use yii\widgets\DetailView;

?>

<div class="box">
    <div class="box-header with-border">
        <?= Html::a('<i class="fa fa-plus"></i> Tambah Jam Operasional', ['/jam-operasional/create','id_operasional' => $model->id], ['class' => 'btn btn-primary btn-flat']); ?>
    </div>

    <div class="box-body">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th style="text-align: center; width: 55px">No</th>
                    <th style="text-align: center">Jam Buka</th>
                    <th style="text-align: center">Jam Tutup</th>
                    <th style="text-align: center; width: 75px"></th>
                </tr>
            </thead>
            <tbody>
                <?php $no = 1; ?>
                <?php /* @var $jamOperasional app\models\JamOperasional */ ?>
                <?php foreach ($model->manyJamOperasional as $jamOperasional) { ?>
                    <tr>
                        <td style="text-align: center;">
                            <?= $no ?>
                        </td>
                        <td style="text-align: center;">
                            <?= $jamOperasional->jam_buka ?>
                        </td>
                        <td style="text-align: center;">
                            <?= $jamOperasional->jam_tutup ?>
                        </td>
                        <td style="text-align: center;">
                            <?= Html::a('<i class="fa fa-pencil"></i>', ['jam-operasional/update','id' => $jamOperasional->id], ['option' => 'value']); ?>
                            <?= Html::a('<i class="fa fa-trash"></i>', ['jam-operasional/delete','id' => $jamOperasional->id], ['data-method' => 'post','data-confirm' => 'Apakah anda yakin akan menghapus data berikut?']); ?>
                        </td>
                    </tr>
                <?php $no++; } ?>
            </tbody>
        </table>
    </div>
</div>

views/operasional/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\OperasionalSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="operasional-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>
        <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'id_hari') ?>

    <?= $form->field($model, 'tanggal') ?>

    <div class="col-sm-2 col-xs-12">
        <?= Html::submitButton('<i class="fa fa-check"></i> Filter Data', ['class' => 'btn btn-primary btn-flat']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/operasional/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Operasional */

$this->title = "Tambah Operasional";
$this->params['breadcrumbs'][] = ['label' => 'Operasionals', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="operasional-create">

    <?= $this->render('_form', [
        'model' => $model,
        'referrer'=> $referrer
    ]) ?>

</div>

views/operasional/index.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\OperasionalSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Daftar Operasional';
$this->params['breadcrumbs'][] = $this->title;
?>
        <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

<div class="operasional-index box box-primary">

    <div class="box-header with-border">
        <?= Html::a('<i class="fa fa-plus"></i> Tambah Operasional', ['create'], ['class' => 'btn btn-primary btn-flat']) ?>

    </div>

    <div class="box-body">

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            [
                'class' => 'yii\grid\SerialColumn',
                'header' => 'No',
                'headerOptions' => ['style' => 'text-align:center;  width: 50px'],
                'contentOptions' => ['style' => 'text-align:center']
            ],
            [
                'class' => 'kartik\grid\ExpandRowColumn',
                'value' => function ($model, $key, $index, $column) {
                    return GridView::ROW_COLLAPSED;
                },
                'detail' => function ($model, $key, $index, $column) {
                    return $this->render('_list-jam-operasional', ['model' => $model]);
                },
                'headerOptions' => ['class' => 'kartik-sheet-style'],
                'expandOneOnly' => true,
            ],
            [
                'attribute' => 'id_hari',
                'format' => 'raw',
                'value' => function($data) {
                    return \app\components\Helper::getHari($data->id_hari);
                },
                'headerOptions' => ['style' => 'text-align:center;'],
                'contentOptions' => ['style' => 'text-align:center;'],
            ],
            [
                'header' => 'Tanggal Input',
                'format' => 'raw',
                'value' => function($data) {
                    return \app\components\Helper::getWaktuWIB($data->tanggal);
                },
                'headerOptions' => ['style' => 'text-align:center; width: 155px'],
                'contentOptions' => ['style' => 'text-align:center;'],
            ],
            [
                'header' => 'Jam Operasional',
                'format' => 'raw',
                'value' => function($data) {
                    return '<span class="label label-success" data-toggle="tooltip" title="Jumlah Jam Operasional">'.count($data->manyJamOperasional).'</span>';
                },
                'headerOptions' => ['style' => 'text-align:center; width: 90px'],
                'contentOptions' => ['style' => 'text-align:center;'],
            ],

            [
                'class' => 'yii\grid\ActionColumn',
                'contentOptions' => ['style' => 'text-align:center;width:80px']
            ],
        ],
    ]); ?>
    </div>
</div>

views/operasional/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Operasional */

$this->title = "Sunting Operasional";
$this->params['breadcrumbs'][] = ['label' => 'Operasionals', 'url' => ['index']];
$this->params['breadcrumbs'][] = 'Sunting';
?>
<div class="operasional-update">

    <?= $this->render('_form', [
        'model' => $model,
        'referrer'=> $referrer
    ]) ?>

</div>

views/operasional/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Operasional */

$this->title = "Detail Operasional";
$this->params['breadcrumbs'][] = ['label' => 'Operasional', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="operasional-view box box-primary">

    <div class="box-header with-border">
        <h3 class="box-title">Detail Operasional</h3>
    </div>

    <div class="box-body">

    <?= DetailView::widget([
        'model' => $model,
        'template' => '<tr><th width="180px" style="text-align:right">{label}</th><td>{value}</td></tr>',
        'attributes' => [
            [
                'attribute' => 'id_hari',
                'format' => 'raw',
                'value' => \app\components\Helper::getHari($model->id_hari),
            ],
            [
                'attribute' => 'tanggal',
                'format' => 'raw',
                'value' => \app\components\Helper::getWaktuWIB($model->tanggal),
            ],
        ],
    ]) ?>

    </div>

    <div class="box-footer">
        <?= Html::a('<i class="fa fa-pencil"></i> Sunting Operasional', ['update', 'id' => $model->id], ['class' => 'btn btn-success btn-flat']) ?>
        <?= Html::a('<i class="fa fa-list"></i> Daftar Operasional', ['index'], ['class' => 'btn btn-warning btn-flat']) ?>
    </div>
</div>


<?= $this->render('_list-jam-operasional',['model' => $model]) ?>